### ISSUE TITLE
Setup.R fails on Ubuntu install_tm.sh

### ISSUE THREAD

**Issue by etournay** [mpicbg-scicomp/tissue_miner#11]
On a real Ubuntu (not a docker VM,) Setup.R  requires sudo to run and however returns an error the way it is implemented in install_tm.sh
Running setup.r in a R session with local installation (not system-wise) works fine.

Below is the error message. Coud you fix this Holger ?

> Loading required package: devtools
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/commons/TMCommons.R': No such file or directory
Execution halted

One idea: creating a .Renviron containing TM_HOME=path_to_TM solved this issue.
But is there a more elegant way to do it ?

In the same line of idea, a local R package install might be less invasive than a system-wise installaiton that my break already existing workflows (system-wise). What do you think about making setup.R installing packages locally, in the user account ? See
https://www.osc.edu/documentation/howto/install-local-R-packages

**Comment by holgerbrandl** [comment]
I don't think that sudo is required to run Setup.R. It is for the dependencies since they need to come via apt-get, but R should install into the user package index without sudo.

At least it works for me.

**Comment by etournay** [comment]
Waouh, you were fast.
Yes, "sudo" was a very dirty fix which I didn't like at all.
Good news then it works without!
I'll try it on a new fresh ubuntu
R


----- Mail original -----
De: "Holger Brandl" <notifications@github.com>
À: "mpicbg-scicomp/tissue_miner" <tissue_miner@noreply.github.com>
Cc: "etournay" <etournay@mpi-cbg.de>
Envoyé: Vendredi 18 Mars 2016 14:26:03
Objet: Re: [tissue_miner] Setup.R fails on Ubuntu install_tm.sh (#11)

I don't think that sudo is required to run Setup.R. It is for the dependencies since they need to come via apt-get, but R should install into the user package index without sudo.

At least it works for me.

---

**Comment by etournay** [comment]
setup.R still fails on a fresh Ubuntu 14.04 trusty
setup.R also fails on a fresh Ubuntu 15.10 Wily with the exact same error message:

> Installing required R packages
> Warning in install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
>   'lib = "/usr/lib/R/library"' is not writable
> Error in install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  : 
>   unable to install packages
> Calls: update.packages -> install.packages
> Execution halted
> The R setup FAILED, please check /home/etournay/tissue_miner/.tm_install_rsetup.log

**Comment by etournay** [comment]
The script now installs the missing ubuntu packages that were not installed due to my space mistake, but the R setup still fails with the same message on both Linux. It only works if I set up the global variables in .Renviron.
> 
> Installing required R packages
> Warning message:
> In normalizePath(userLibDirectory) :
>   path[1]="/home/etournay/R/x86_64-pc-linux-gnu-library/3.2": No such file or directory
> Loading required package: codetools
> Loading required package: devtools
> Installing package into ‘/usr/local/lib/R/site-library’
> (as ‘lib’ is unspecified)
> Warning in install.packages("devtools") :
>   'lib = "/usr/local/lib/R/site-library"' is not writable
> Error in install.packages("devtools") : unable to install packages
> In addition: Warning message:
> In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called ‘devtools’
> Execution halted
> The R setup FAILED, please check /home/etournay/tissue_miner/.tm_install_rsetup.log
> 
> 
>

**Comment by etournay** [comment]
The "userLibDirectory" is created, but .libPaths() isn't updated.
There are different ways of fixing this issue:

- set global variables in .Rprofile.site prior to setup.R execution also running .libPaths(.libPaths()) (not tested).

- add the option lib=userLibDirectory in all commands 'install.packages' (it works !)

- run the local lib folder creation in one script and run a second script for the rest (it works= if I run the setup.R twice, it always fails the first time because the local lib folder doesn't exist, and it runs through the second time because the local lib folder is already present).

Is it possible to find an elegant way of fixing this issue ?

**Comment by etournay** [comment]
Well, and what about running:
`.libpaths(normalizedPath(userLibDirectory))`

It works and I find it elegant enough, don't you ?

**Comment by holgerbrandl** [comment]
Nice fix.
