### ISSUE TITLE
Misleading landing page reference to macro-UI

### ISSUE THREAD

**Issue by holgerbrandl** [mpicbg-scicomp/tissue_miner#12]
Concerning:
> TissueMiner also contains a GUI [here](fiji_macros/draw_n_get_ROIcoord.ijm) to group cells (ROI's) in space, and a lineage browsing algorithm to follow these ROI's backward and forward in time.

The link to a ijm file is not what I'd associate with a ui and I'd guess most users will either. The link should rather go into the batch-processing guide where we detail out how to prep movies for processing, and in particular how to use the macro in fiji to draw ROIs

**Comment by etournay** [comment]
Moved and reorganized in MovieProcessing.md
