### ISSUE TITLE
Should the configuration of .bash_profile be part of the installation on Ubuntu ?

### ISSUE THREAD

**Issue by etournay** [mpicbg-scicomp/tissue_miner#14]
I would find natural that the installer also sets up the .bash_profile by adding lines in it if they don't already exist. We would then have the complete intallation in one single script.

```
## adjust your path to include the tissue_miner folder
export TM_HOME="~/tissue_miner"

## adjust your path to include all tools for execution
export PATH=$TM_HOME/db:$TM_HOME/shear:$TM_HOME/roi:$TM_HOME/misc:$TM_HOME/movies:$TM_HOME/shear_contributions:$TM_HOME/topology:$TM_HOME/triangles:$TM_HOME/lineage:$PATH
export PATH=${TM_HOME}/parser:$PATH

## defines an alias for the snakemake command line
sm() {
    snakemake --snakefile ${TM_HOME}/workflow/tm.snkmk --keep-going "$@"
}
export -f sm
```
see:
[here](http://stackoverflow.com/questions/4749330/how-to-test-if-string-exists-in-file-with-bash-shell)

**Comment by etournay** [comment]
On Linux, the .bashrc is sources by default, not the .bash_profile in contrast to osx. 
[see](http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html)

**Comment by holgerbrandl** [comment]
Usually tools leave bashrc modifications to the user to prevent PATH pollution etc.
