### ISSUE TITLE
render_movie() crashes on OSX when .parallel=T, but runs fine if .parallel=F

### ISSUE THREAD

**Issue by etournay** [mpicbg-scicomp/tissue_miner#15]
On an up-to-date tissue_miner installation on OSX, including a fresh run of Setup.R, the `render_movier()` function crashes only if parallelization is enabled. 

> [1] "Creating cell_area_pattern.mp4..."
> using temporary directory /var/folders/30/q9h8zhpd3ts23ql_d38jm9480000gp/T//RtmpqPzUfM/file23bf566682a3/
> Progress disabled when using parallel plyr
> processing  0 ...
> processing  1 ...
> processing  2 ...
> 
>  **\* caught segfault ***
> address 0x110, cause 'memory not mapped'
> 
> Traceback:
>  1: grDevices::png(..., res = dpi, units = "in")
>  2: dev(file = filename, width = dim[1], height = dim[2], ...)
>  3: ggsave(outputFile, gg, width = 12, height = 5)
>  4: .fun(piece, ...)
>  5: do.ply(i)
>  6: eval(expr, envir, enclos)
>  7: eval(c.expr, envir = args, enclos = envir)
>  8: doTryCatch(return(expr), name, parentenv, handler)
>  9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
> 10: tryCatchList(expr, classes, parentenv, handlers)
> 11: tryCatch(eval(c.expr, envir = args, enclos = envir), error = function(e) e)
> 12: FUN(X[[i]], ...)
> 13: lapply(X = S, FUN = FUN, ...)
> 14: doTryCatch(return(expr), name, parentenv, handler)
> 15: tryCatchOne(expr, names, parentenv, handlers[[1L]])
> 16: tryCatchList(expr, classes, parentenv, handlers)
> 17: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
> 18: try(lapply(X = S, FUN = FUN, ...), silent = TRUE)
> 19: sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE))
> 20: FUN(X[[i]], ...)
> 21: lapply(seq_len(cores), inner.do)
> 22: mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,     mc.silent = silent, mc.cores = cores)
> 23: e$fun(obj, substitute(ex), parent.frame(), e$data)
> 24: foreach::`%dopar%`(fe, do.ply(i))
> 25: llply(.data = pieces, .fun = .fun, ..., .progress = .progress,     .inform = .inform, .parallel = .parallel, .paropts = .paropts)
> 26: dlply(subset(celldata, frame%%sampleRate == 0), .(frame), function(csFrame) {    curFrame <<- unique(csFrame$frame)[1]    echo("processing ", curFrame, "...")    gg <- render_source_image(curFrame, ...) %+% csFrame    if (is.list(cellLayers)) {        for (i in 1:length(cellLayers)) {            gg <- gg + cellLayers[i]        }    }    else {        gg <- gg + cellLayers    }    outputFile = paste0(filePrefix, sprintf("%03d.png", curFrame))    ggsave(outputFile, gg, width = 12, height = 5)    if (createSvgZip) {        svgFile = paste0(filePrefix, sprintf("%03d.svg", curFrame))        ggsave(svgFile, gg, width = 12, height = 5)    }}, .progress = "text", .parallel = T, .drop = F)
> 27: render_movie(cellArea, "cell_area_pattern.mp4", list(geom_polygon(aes(x_pos,     y_pos, group = cell_id, fill = area)), scale_fill_gradientn(name = "area (px)",     colours = c("black", "blue", "green", "yellow", "red"), limits = c(0,         quantile(cellArea$area, probs = 99.9/100)), na.value = "red")))
> aborting ...

**Comment by holgerbrandl** [comment]
Seems related to http://stackoverflow.com/questions/25672974/caught-segfault-error-in-r

In fact it's not a TM bug but rather a ggplot/dplyr issue. I've filed a ticket under https://github.com/hadley/ggplot2/issues/1600

**Comment by johnjosephwilliamson** [comment]
Hi guys,

I am trying out the R tutorials for TM and think I am affected by this problem. Trying cell_area_pattern.R produces the exact memory error as above, and in addition trying 1.8.4 example 4 from here (https://mpicbg-scicomp.github.io/tissue_miner/tm_tutorial/R-tutorial.html#setup-tissueminer-routines-and-rstudio) produces an error "Error: all(movieNames %in% algnModel$movie) is not TRUE". Since this is the first tutorial example on that page to involve the render_frame() function, perhaps my two problems are related.

Anyway, to get me through the tutorial for now, what is the best way for me to globally set .parallel=F? I am on OS X 10.11.4 and have installed TM using docker.

Thanks,
John

**Comment by etournay** [comment]
Dear John,

Thank you for using TissueMiner and for bringing this issue to us.
TissueMiner is current beeing revised in deepth to simplify its use by a novice. This will take about two weeks from now, and the current huge R-tutorial will be simplified in the next few weeks.

We are currenly fixing issues in **Ubuntu** first since this Linux is also used to generate the docker image to be used under MacOS. If you see the [quickstart tutorials ](https://github.com/mpicbg-scicomp/tissue_miner#documentation),  only one link is active: "Ubuntu with example data". 

Next week I'll take care of the MacOS tutorials using docker. 

Both error mesages are not related.

We are working on the memory issue that recently came up with a R update.

The second error "Error: all(movieNames %in% algnModel$movie) is not TRUE" is due to the fact that your movie name is not present in the config file. This will be documented very soon. I'll keep you posted. We are currently working on the tutorials and documentation.
Best wishes
Raphael

**Comment by etournay** [comment]
Ok, from your EDIT, I see that you are  also using TM locally on your mac.

That also works if you have already built the database corresponding to your movie (using docker).
You first need to install avconv on MacOS and run the setup.R in your Rstudio or equivalent.

From the big master Guide, you've got this line in your script:

`source(file.path(scriptsDir, "config/flywing_tm_config.R"))`

Please, replace it with :
`source(file.path(scriptsDir, "config/default_config.R"))`

**Comment by johnjosephwilliamson** [comment]
Dear Raphael,

Thanks so much for the further info. As you mentioned, I have libav installed and then I ran the Setup.R script from within R studio. It seems to have worked although there is something “rgeos” which does not compile properly, or if I select to install the binary seems to work but I’m not sure (I am a novice at interpreting R output too). If I subsequently re-run Setup.R I am asked about rgeos again, hence my worry.

In any case, I also corrected the config file as you said, and now the example using render_frame works correctly. Thank you! I will be sure to keep an eye on the upcoming changes you are making, for now I am enjoying getting to grips with how TM works and what it can do.

John

John J. Williamson
jjw@fastmail.com
old email: johnjosephwilliamson@gmail.com

**Comment by etournay** [comment]
@johnjosephwilliamson 

Under linux, rgeos requires the installation of a dedicated library 
`sudo apt-get install -y libgeos-dev`

On MacOs, this library seems to be required too (hence a docker image to avoid struggling with local installation on every system). But the pieces of code that are present in the tutorials shouldn't use this library anyway. As long as the tutorial scripts work without error, it is an indication that this library isn't used. I will check that next week when dealing with the osx tutorials.
Raphael

**Comment by johnjosephwilliamson** [comment]
@etournay thanks for that. FYI, I installed the geos package through MacPorts, and the Setup.R now seems to complete properly.

**Comment by etournay** [comment]
@holgerbrandl 
Hi Holger, shall we write a small patch to disabled parallel in the render_movie function only on Mac?
I currently have two versions which is annoying.
Best, Raphael

**Comment by holgerbrandl** [comment]
disabling parallel movie rendering on mac sounds good to me. just reassign to me if necessary, but I'm booked out this week.

**Comment by etournay** [comment]
OK, then better focus on issue#22.
Cheers,
R


----- Mail original -----
De: "Holger Brandl" <notifications@github.com>
À: "mpicbg-scicomp/tissue_miner" <tissue_miner@noreply.github.com>
Cc: "Raphael Etournay" <etournay@mpi-cbg.de>, "Mention" <mention@noreply.github.com>
Envoyé: Mardi 26 Avril 2016 06:32:16
Objet: Re: [mpicbg-scicomp/tissue_miner] render_movie() crashes on OSX when .parallel=T, but runs fine if .parallel=F (#15)

disabling parallel movie rendering on mac sounds good to me. just reassign to me if necessary, but I'm booked out this week.

---

**Comment by etournay** [comment]
I changed `.parallel=T` into `.parallel=!(Sys.info()["sysname"]=="Darwin")` to temporarily fix this current issue.

**Comment by etournay** [comment]
Using docker solves this issue
