### ISSUE TITLE
Silent require.auto()

### ISSUE THREAD

**Issue by etournay** [mpicbg-scicomp/tissue_miner#16]
When running the sm workflow, lots of parasite messages come from the too verbose require.auto() function. These messages **must be hidden** in TissueMiner.
Could you add a second argument to require.auto(), namely warn.conflicts = F ?
Example inside require.auto():
`eval(parse(text=paste("require(", x, ", warn.conflicts = F, quietly=T)", sep="")))`

I would then use require.auto(package, warn.conflicts = F) all through TissueMiner.
Best, 
Rapha

**Comment by holgerbrandl** [comment]
see my uncommitted changes in tissue_miner/commons/TMCommons.R
They completely silence the initial package loading process:
```
> source("/Volumes/projects/project-raphael/scripts/tissue_miner/commons/TMCommons.R")
[1] "using config file /Volumes/projects/project-raphael/scripts/tissue_miner/config/default_config.R"
```

Since this is what most of our tools use, this might be sufficient already. We would have to inline core_commons.R and patch it according to your suggestion, if you think that the solution is not general enough. However, in fact I like those conflict warnings since they indicate potential namespace conflicts.

**Comment by etournay** [comment]
I have tried it and it works the expected way. But it seems like using `sink()` afterwards does not re-establish the verbose mode. Anyway you can commit it so that I try it in the Linux tuto. Many thx. R

**Comment by holgerbrandl** [comment]
The state is restored in `commons/TMCommons.R:28` where we call `sink()` without any arguments. Works for me on macos and linux.

**Comment by etournay** [comment]
sink() doesn't restore the verbose mode. In particular, error messages are hidden in case of crash. Sorry...

**Comment by etournay** [comment]
sink(file=NULL, , type="message") send messages back to the console

**Comment by holgerbrandl** [comment]
so what was your final conclusion here?

**Comment by etournay** [comment]
`sink(file=NULL, , type="message")` works on epc and my mac, but  `sink()` doen't.

**Comment by holgerbrandl** [comment]
indeed my initial patch was not good and just restored "output" (which was not sinked). Using the correct type here is right thing to do. There's no need to specify `file=NULL` since it's the default anyway, but maybe you did it this way to clarify the purpose.

**Comment by etournay** [comment]
Genau !
