### ISSUE TITLE
Make tm.snmk working without LastFrameRoi.txt

### ISSUE THREAD

**Issue by etournay** [mpicbg-scicomp/tissue_miner#17]
Currently, one has to define at least one ROI manually to use the sm workflow. By default the sm workflow should create the whole_tissue ROI, therefore the manual ROI definition should be just an option. 

Additionally, I would rename _LastFrameRoi.txt_ into _userRois.txt_ in the entire pipeline... (tedious !)

**Comment by holgerbrandl** [comment]
makes sense I'll have a look but not before end of next week

**Comment by etournay** [comment]
Done ! Included in the new UserRoiTracking.R script. I propagated changes in all related files by using "search in files" in RStudio.
