### ISSUE TITLE
lineage movie rule fails if no division occurs

### ISSUE THREAD

**Issue by etournay** [mpicbg-scicomp/tissue_miner#20]
enhance LineageMovies.R

**Comment by holgerbrandl** [comment]
you need a more pretty avatar picture! The current almost looks like background with a few broken pixels. :-)

**Comment by holgerbrandl** [comment]
Yeah, now I can spot you! Very eye-catchy :+1:

**Comment by etournay** [comment]
Just a little more pixels...

**Comment by etournay** [comment]
Fixed and tested on computer generated cells data.
