### ISSUE TITLE
Class ambiguity from `frames4merge <- unlist(apply(with(cellMinMax,...` in CreateDbFromParser.R#L271 causes crash

### ISSUE THREAD

**Issue by etournay** [mpicbg-scicomp/tissue_miner#22]
Hi Holger, 

When running sm make_db on the sample called "original" that I'll send you by email, I get the following message:

> 1] "replacing cell IDs in dbonds..."
> Error in setkeyv(value, key) : 
>   some columns are not in the data.table: frame
> Calls: dt.merge ... as.df -> as.data.frame -> merge -> data.table -> setkeyv
> Execution halted
> Error in job make_db while creating output files original.sqlite, cellshapes.RData.
> RuleException:
> CalledProcessError in line 58 of /tissue_miner/workflow/tm.snkmk:
> Command 'CreateDbFromParser.R /movies/original' returned non-zero exit status 1
>   File "/tissue_miner/workflow/tm.snkmk", line 58, in __rule_make_db
>   File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
> Job failed, going on with independent jobs.
> Exiting because a job execution failed. Look above for error message

the `frames4merge` variable should be a suite of integers, but it becomes a matrix when running the script on the example. It sounds like a coercion issue.

[go here](https://github.com/mpicbg-scicomp/tissue_miner/blob/master/db/CreateDbFromParser.R#L271)

Could you fix this ?

**Comment by holgerbrandl** [comment]
I'll have a look asap

**Comment by etournay** [comment]
It think I was rigth about the coercion issue. Here is the documentation of the `unlist()` funtion in R:

> The output type is determined from the highest type of the components in the hierarchy NULL < raw < logical < integer < double < complex < character < list < expression, after coercion of pairlists to lists.

Could you fix that as soon as possible ?

Best,

Raphael
