### ISSUE TITLE
 installing *source* package ‘png’ ... locally in R 3.3 crashes

### ISSUE THREAD

**Issue by etournay** [mpicbg-scicomp/tissue_miner#25]
> " thomas@thomas-Workstation:~/example_data/demo$ cell_area_pattern.R . output_analysis
> [1] "/home/thomas/example_data/demo"
> [1] "/home/thomas/example_data/demo/output_analysis"
> [1] "raw"
> Warning message:
> In dir.create(outDir) :
>   '/home/thomas/example_data/demo/output_analysis' existe déjà
> * installing *source* package ‘png’ ...
> ** package ‘png’ correctement décompressé et sommes MD5 vérifiées
> ** libs
> gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      `libpng-config --cflags` -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c read.c -o read.o
> gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      `libpng-config --cflags` -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c write.c -o write.o
> gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o png.so read.o write.o -L/home/thomas/anaconda3/lib -lpng16 -lm -lz -lm -L/usr/lib/R/lib -lR
> installing to /home/thomas/R/x86_64-pc-linux-gnu-library/3.3/png/libs
> ** R
> ** inst
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded
> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
>   impossible de charger l'objet partagé '/home/thomas/R/x86_64-pc-linux-gnu-library/3.3/png/libs/png.so':
>   libpng16.so.16: cannot open shared object file: No such file or directory
> Erreur : le chargement a échoué
> Exécution arrêtée
> ERROR: loading failed
> "

**Comment by holgerbrandl** [comment]
hmm, works for me when using centos.

**Comment by etournay** [comment]
hmm, also works for me on Ubuntu 14.04 Mint Mate 17.3
It seems like some Ubuntu versions do not have the same set of dependencies:
[on stackoverflow is a possible solution for this issue](https://stackoverflow.com/questions/35902205/install-package-png-in-r-ubuntu)
