### ISSUE TITLE
Feature: TM needs Internet connection to work

### ISSUE THREAD

**Issue by etournay** [mpicbg-scicomp/tissue_miner#26]
TMcommons loads the following modules from the network

> devtools::source_url("https://raw.githubusercontent.com/holgerbrandl/datautils/v1.13/R/core_commons.R")
> devtools::source_url("https://raw.githubusercontent.com/holgerbrandl/datautils/v1.13/R/ggplot_commons.R")
> devtools::source_url("https://raw.githubusercontent.com/holgerbrandl/datautils/v1.13/R/datatable_commons.R")

This implies that TM requires a working Internet connection to run. We should either mention it as a requirement or bring the foreign packages in the docker Image !

**Comment by holgerbrandl** [comment]
If you think that internet should not be required, you could simply put the 3 files into ./commons and source them from there.

**Comment by etournay** [comment]
Well hard to tell, people are usually connected. I'll take some time to ask around and decide...

**Comment by etournay** [comment]
Switched to local mode with all libraries copied locally. Does not need network connection anymore to run.
