### ISSUE TITLE
sm make_db

### ISSUE THREAD

**Issue by arkyaC** [mpicbg-scicomp/tissue_miner#27]
Which software do I need to install for running this command?
I tried `sudo apt-get install sm`
But this software just prints "make_db" on my screen in huge letters when I run `sm make_db`
Appreciate any help.

**Comment by holgerbrandl** [comment]
`sm` is just a bash-function wrapper around `snakemake` https://bitbucket.org/johanneskoester/snakemake/wiki/Home . See https://github.com/mpicbg-scicomp/tissue_miner/blob/7a6bb1ffe2da42a17750e6ab83c8d98e635af24c/installation/ubuntu/tm_profile.txt#L6

But actually there should no need to install it manually, since the snakemake installation is covered by the installer of TIssueMiner, see https://github.com/mpicbg-scicomp/tissue_miner/blob/master/installation/local_installation.md#ubuntu

To avoid all the installation hassle you could also run it via docker (recommended). See https://github.com/mpicbg-scicomp/tissue_miner#installation-inside-docker

**Comment by arkyaC** [comment]
Actually I'm new to docker. Could you help me out with how exactly to "run it via docker"? 
Thanks

**Comment by holgerbrandl** [comment]
Sure, I'd suggest get started by working through our tutorials on https://github.com/mpicbg-scicomp/tissue_miner#documentation . Feel welcome to come back to us if something not clear.

**Comment by arkyaC** [comment]
When I run the command `tm sm make_db` (the very first command in the tutorials, after downloading the sample data), I get this:
`sudo: tm: command not found`

**Comment by holgerbrandl** [comment]
tm is an alias. See https://github.com/mpicbg-scicomp/tissue_miner/blob/gh-pages/quickstart_tutorial/other_os/tm_qs_example_data.md#2-download-the-example-data-set-100-mb

**Comment by arkyaC** [comment]
I added the alias, but still I got the error message, I think it could be due to the fact that I couldn't get the docker quickstart terminal running.

**Comment by holgerbrandl** [comment]
You don't need a quickstart terminal when using ubuntu.

1. Just pull the image (see https://github.com/mpicbg-scicomp/tissue_miner#installation-inside-docker)
3. fetch demo data (or prepare your own data, and configure your environment (see https://github.com/mpicbg-scicomp/tissue_miner/blob/gh-pages/quickstart_tutorial/other_os/tm_qs_example_data.md#2-download-the-example-data-set-100-mb)
2. run it (see https://github.com/mpicbg-scicomp/tissue_miner/blob/gh-pages/quickstart_tutorial/other_os/tm_qs_example_data.md#3-select-the-analysis-you-are-interested-in). Don't forget quotes around the arguments given to tm!

**Comment by arkyaC** [comment]
I followed this (edited .bashrc), and got this output:
```
jarvis@jarvis-Inspiron-5558:~/example_data/demo$ tm "sm shear_calculate topo_countt1 polygon_class tri_categorize; analyze_movie.R . output_analysis"
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
jarvis@jarvis-Inspiron-5558:~/example_data/demo$ sudo tm "sm shear_calculate topo_countt1 polygon_class tri_categorize; analyze_movie.R . output_analysis"
[sudo] password for jarvis: 
sudo: tm: command not found
```

**Comment by holgerbrandl** [comment]
This is a docker setup issue, which is out of the scope of TissueMiner. Just search the web, which contains different solutions to overcome this problem.

**Comment by arkyaC** [comment]
"CAUTION for Linux Users: this only works if your user ID is 1000. We are working on a more generic solution for any user"
Could the problem I mentioned be due to this? How do I check my user ID on a linux machine?

**Comment by arkyaC** [comment]
The problem is probably due to the alias not being created properly when I update the .bashrc, which is not a TissueMiner problem. Thanks a lot @holgerbrandl for all the help.
