### ISSUE TITLE
Issue with tutorial for R

### ISSUE THREAD

**Issue by arkyaC** [mpicbg-scicomp/tissue_miner#28]
The following statement is placed under the TissueMiner User Manual (with R), under section 1.1.3.1

> go to the fiji_macros folder located in your TissueMiner installation folder

Could you help me regarding how to access this folder, since I installed this by pulling the docker image, and not physically on my computer (Ubuntu 14.04)?

**Comment by etournay** [comment]
Hello, 
Thank you for your comments on the Manual. This sentence was actually outdated and I therefore just updated the Manual accordingly.
The easiest is that you get the fiji macros directly from github by clicking on the links I now provide in the Manual.
Of note, Fiji isn't meant to work from the docker tool. You need to install Fiji beside the dockerized TissueMiner.
Don't hesitate to ask this is still unclear.
Best wishes

**Comment by arkyaC** [comment]
Yes, got it. So, I installed the Fiji software directly on my Ubuntu machine, and pulled the TissueMiner image from etournay/tissue_miner , as you wrote in the instructions.
Thanks a ton!
