### ISSUE TITLE
How to make the culumtimesec.txt file

### ISSUE THREAD

**Issue by StephenWallin** [mpicbg-scicomp/tissue_miner#29]
I have been working on getting tissue_miner up and running for image analysis the past few days. I was able to start analysis on the demo data set. However, when attempting to start analysis on data acquired in our lab (Zeiss Confocal, .czi), I have no culumtimesec.txt file required for the snakemake workflow. There is no information in any of the tutorials or guides on how to create this file from a data set. Is there a step that I am missing? I have processed the set of images using the Tissue Analysis plugin in ImageJ.

**Comment by etournay** [comment]
Dear Stephen,

Thank you for using TM. You are right , I should clarify this point in the documentation.
In the meantime, you may just create a cumultimesec.txt in Excel, starting from 0, and save as txt.
Of course it would be ideal to parse the metadata from the czi file, and in particular if the time interval isn't constant. I haven't worked with czi files but you may solve this issue using Fiji.

Best wishes

**Comment by StephenWallin** [comment]
May I ask what the format of the excel document should be? Start at 0, and then the time point of each separate image in seconds? Do the time points need to be labelled correspondingly to the name of each image in the time lapse? I can access the metadata file after exporting the .czi as a tiff, so that route is also available. I apologize in advance, I am very inexperienced with programming.

**Comment by etournay** [comment]
You can also use a text editor, but it is easier in Excel.
Example: let's assume that the time interval between frames is about 60sec, then you open Excel, type in 0 on the first line and 60 on the second line. You select both lines, you locate your mouse pointer on the little square at the bottom right of your selection, and you extend the whole thing towards the bottom.  If you have a movie of 20 frames, then you should have 20 lines in your Excel sheet. That's all. And then you save as .txt, not .xls.

Parsing metadata usually requires some programming skills in Fiji. There are so many microscope formats, therefore I don't provide any tools to do that. In my case, I used Axiovision, which is not used anymore. My tool wouldn't work for you. Best would be that you find somebody around you who knows a little about Fiji scripting. Scripting is not hard but it takes time for a novice.

**Comment by StephenWallin** [comment]
Thank you for the quick responses!

I've started analysis on some of our data sets but I am running into some issues with the display of cell shape in the output movies. During segmentation, I have been manually editing junctions to ensure correct cell shape and outline. I have attached image produced during segmentation of the cell tracking as well as what is displayed on the movie produced. You can see that it appears to accurately project the area of the cell (based on the color), but inaccurately masks the cell boundaries. Is there something I am missing during segmentation, or a setting of the analyses that I can change to more accurately fit the cell shape? 

One of the issues we may be having could be due to the mosaic expression of our cell boundary reporter. We do have movies with the entirety of the epithelium labelled, but you run into issues with the z-stack projection showing both the top and bottom layers overlapped.



![tracked_cells_resized](https://cloud.githubusercontent.com/assets/25333988/22388545/a1388186-e4a6-11e6-969b-af38c5a28cd9.png)
![movies example](https://cloud.githubusercontent.com/assets/25333988/22388551/a5be0d7a-e4a6-11e6-8a9c-660900eb4742.png)

**Comment by etournay** [comment]
Hi Stephen, 
I have moved your last comment because it's a different issue.
I therefore opened a new issue #30 . Lets discuss this there.

I'll close this current issue when the tutorial will be updated...
