### ISSUE TITLE
Utiltity methods should have more consistent names

### ISSUE THREAD

**Issue by holgerbrandl** [mpicbg-scicomp/tissue_miner#3]
We should use a more consistent method naming scheme in
* TMCommons.R
* RoiCommons.R
* MovieFunctions.R
ie. underscores and lower capitalized names (which is basically the dplyr naming convention)

Polishing it would be easy, however, I don't want to break your unpublished tutorial so I'm not sure about how to proceed.

**Comment by etournay** [comment]
Go ahead, it's piece of cake to update the R-tutorial

**Comment by etournay** [comment]
Names are currently consistent. We don't have to follow another convention.
