### ISSUE TITLE
Cells at the margin of the segmentation mask are not displayed entirely

### ISSUE THREAD

**Issue by etournay** [mpicbg-scicomp/tissue_miner#30]
FROM StephenWallin:

I've started analysis on some of our data sets but I am running into some issues with the display of cell shape in the output movies. During segmentation, I have been manually editing junctions to ensure correct cell shape and outline. I have attached image produced during segmentation of the cell tracking as well as what is displayed on the movie produced. You can see that it appears to accurately project the area of the cell (based on the color), but inaccurately masks the cell boundaries. Is there something I am missing during segmentation, or a setting of the analyses that I can change to more accurately fit the cell shape? 

One of the issues we may be having could be due to the mosaic expression of our cell boundary reporter. We do have movies with the entirety of the epithelium labelled, but you run into issues with the z-stack projection showing both the top and bottom layers overlapped.

![tracked_cells_resized](https://cloud.githubusercontent.com/assets/25333988/22388545/a1388186-e4a6-11e6-969b-af38c5a28cd9.png)
![movies example](https://cloud.githubusercontent.com/assets/25333988/22388551/a5be0d7a-e4a6-11e6-8a9c-660900eb4742.png)

**Comment by etournay** [comment]
Hi Stephen,

This issue is actually a normal behavior of TM. It's a feature.

The reason is that cell contours are not stored in the database, only vertices are stored. Cell contours are therefore interpolated between successive vertices hence the polygonal looking. 

A vertex is defined as one pixel at the interface of at least 3 cells. At the margin, this definition does not hold in general because you don't provide this information in the segmentation mask. Therefore one or more vertices are missing and cell contours are truncated.  

This strategy is very fast and allows users to display millions of cells in a reasonable amount of time (compared for example with Tissue Analyzer). The drawback is that margin cells cannot be displayed entirely although their attributes (area, perimeter, elongation, polarity tensor, etc...) are correct because they were calculated from the images before assembling the database.

We already know solutions to fix that. However, that wasn't our priority to implement one of them because cells at the margin of large tissues  (20000 to 50000 cells per frame) are usually badly segmented or moving out the field of view, and we discard them by default when tracking the lineages. For example, you could specify the "whole_tissue" roi and you'll see that all cells lining the margin will be discarded.

For small-scale analysis TissueAnalyzer deos a very good job and is usually sufficient. If you have lots of clones at a large scale, then we may implement a better solution for display. But keep in mind that those margin cells have correct attributes. 

For you, the solution would be to assign each cell a dot in its center Instead of displaying polygons. Using ggplot2 in R, the size of the dots could be easily scaled to the cell area, and the color scaled to the area too using a gradient scaling. I would go for this solution that most of my colleagues use because it's even faster than displaying polygons (physicists are more pragmatic).
Just drop me a line if you don't see how to to do that.

Best, 
Rapha

**Comment by StephenWallin** [comment]
Rapha,

Your help has been greatly appreciated. I did notice that the cells on the edge of the image were not masked in the example data. Most of the images that we gather have mosaic expression in the membranes, meaning that most cells will have missing vertexes.  

I am unsure on how to follow up with this in R. As I have noted, I am very inexperienced but willing to learn. It would take me hours of troubleshooting to get this working, whereas I'm sure it only takes you a few minutes to make a script. I have the ggplot2 package installed, and I'm sure I need a package to read .tiff files. But aside from that, I have no idea how to utilize the functions of each package to complete this task.

Stephen

**Comment by etournay** [comment]
Hi Stephen,

The script somehow already partially exists in the [Manual](https://mpicbg-scicomp.github.io/tissue_miner/user_manual/TM_R-UserManual_v1.0.1.html#cell-area). Instead of using `geom_polygon()` you should use `geom_point()`.

However this requires you already manage how to run and use [Rstudio from the docker image.
](https://mpicbg-scicomp.github.io/tissue_miner/user_manual/TM_R-UserManual_v1.0.1.html#how-to-set-up-tissueminer-for-running-api) It also requires that you follow the Manual step by step until the area bit.

The whole point here is that I already created functions (API) to query the database for most common task like area. Then I provide the piece of code for plotting as well as for making movies.

Cheers,
R

**Comment by StephenWallin** [comment]
Rapha,

The docker scripts have worked extremely well so far with our lines that have complete labeling of membranes.

However, I am running into issues while running through the Rstudio manual.

I have followed all steps up to this section.

>  #Load TissueMiner libraries
>source(file.path(scriptsDir, "commons/TMCommons.R"))
>source(file.path(scriptsDir, "db/movie_rotation/RotationFunctions.R"))
>source(file.path(scriptsDir, "commons/BaseQueryFunctions.R"))
>source(file.path(scriptsDir, "commons/TimeFunctions.R"))
>source(file.path(scriptsDir, "config/flywing_tm_config.R"))

I have the correct .bash_profile and have created the .Renviron file, but I cannot get the libraries to load. I keep getting the following error

>Error in eval(expr, envir, enclos) : TM_HOME not correctly defined (  )

I have TM_HOME=C:/Users/gtelab/tissue_miner in my .Renviron. I have also tried with TM_HOME=~/tissue_miner. I have needed to add the full address (C:/Users/gtelab) in order to avoid the error 

>Error in file(filename, "r", encoding = encoding) : 
> cannot open the connection
>In addition: Warning message:
>In file(filename, "r", encoding = encoding) :
> cannot open file '/commons/TMCommons.R': No such file or directory

Is there something I am missing here?

Thank you so much

Stephen

**Comment by etournay** [comment]
Sorry for the delay, I took a week off.
You may try the following path (without the tilde):
`TM_HOME=/tissue_miner`
An outdated path in the Manual, ... one more thing on the todo list...

**Comment by StephenWallin** [comment]
No worries! 

This path does not work either, I get the same "no such file or directory" error with TM_HOME=/tissue_miner. 

Changing the source function to
>source("C:/Users/gtelab/tissue_miner/commons/TMCommons.R")
gives me the error
>Error in eval(expr, envir, enclos) : TM_HOME not correctly defined (  )
still as well. That format is the only way I can get the function to even recognize the TMCommons.R file.

**Comment by StephenWallin** [comment]
I still get that error when running Rstudio through the Rstudio program, however it works perfectly fine on the Rstudio run through my browser. I used the exact same code for both, and only run into the error loading the libraries on the program. It may be worthwhile to clarify that you must use the docker port of Rstudio to the browser instead of the Rstudio program.

**Comment by etournay** [comment]
Hi Stephen, 

Indeed this is what I said in a previous comment above:

> However this requires you already manage how to run and use Rstudio from the docker image.

It would also run with a local Rstudio installation, but it takes about an hour to configure it due to C++ code compilation. Then I will make the docker-Rstudio mendatory in the manual to avoid confusion.

From the  docker-Rstudio you can access all of your data provided you mount the corresponding share using the `-v` option as documented in the Manual. Using the Docker Toolbox on Win or MacOS, you may have to tune VirtualBox a bit as mentionned in the Appendix of the Manual.

Happy coding !

**Comment by StephenWallin** [comment]
I am so sorry, I  did not understand that initially. I am once again running into issues. I apologize for continuing to badger you with questions. The current roadblock for me is that I cannot change the working directory. I have tried on two separate machines thinking that permissions may be at play, but both spit out the same error.

>mcdir(outDataBaseDir)
Error in setwd(dirname) : cannot change working directory
In addition: Warning message:
In dir.create(dirname) :
  cannot create dir '/home/Example_data/demo/output_analysis', reason 'No such file or directory'

Even when I try setwd() I get the same error

> setwd("/home/example_data")
Error in setwd("/home/example_data") : cannot change working directory

I can choose a working directory through the session -> set working directory function. I do not know what the disconnect is here between the two.

My whole script is the following

>movieDbBaseDir="/home/Example_data"
movieDir <- file.path(movieDbBaseDir, c("demo"))
outDataBaseDir=file.path(movieDir, "output_analysis")
scriptsDir=Sys.getenv("TM_HOME")
source(file.path(scriptsDir, "commons/TMCommons.R"))
source(file.path(scriptsDir, "commons/BaseQueryFunctions.R"))
source(file.path(scriptsDir, "commons/TimeFunctions.R"))
source(file.path(scriptsDir, "config/flywing_tm_config.R"))
mcdir(outDataBaseDir)
setwd("/home/example_data")

Where the path to my output_analysis on the example data is /Home/Example_data/demo/output_analysis

Thank you again!
Stephen

**Comment by etournay** [comment]
Hi Stephen,

Your script has a correct syntax. The problem seems to be that the path you specified does not exist. It should contain at least `/home/rstudio`. And paths are key sensitive. To check the path to the demo movie, you may use the following procedure in the docker-Rstudio:
go to Tools>Shell... and type in `pwd` inside the popup window + Enter. This returns the default path "/home/rstudio". From this location, you can navigate through folders by using the unix `cd` command and list files by using the unix `ls` command. Then you can again display the full path corresponding to where you are located using the `pwd` command.

You need to know that by default on Unix systems the user account is located in /home. Then, I defined a user account called rstudio, the only place where you have permission to write files.
When you started the rstudio server from the docker image you may have specified mounting points using the `-v` option. If you did things properly, your data should be accessible from within `/home/rstudio/`. And you don't have permission to write into `/home`, in contrast to `/home/rstudio`. Therefore you should revise the paths you defined above, they cannot work.

Best

**Comment by StephenWallin** [comment]
I appreciate the quick response, this worked perfectly. I see now how straight forward that should have been. I was caught up on the  MUST BE EDITED BY THE USER comment, and since the path to my file did not go through a "Rstudio" folder, I did not include that part. I'm not sure if these comments are helpful for you to help inexperienced programmers. If they are, I will continue to provide my train of thought. 

After running the "Overlay of cells and vertices on the image" for the example data set, I have received this error

> Error: all(movieNames %in% algnModel$movie) is not TRUE

**Comment by etournay** [comment]
Sure, comments are always welcome. 

Regarding the error message, do you get this message with the provided example data or only with your data ?

**Comment by StephenWallin** [comment]
With both my data and the example data. I found a fix in one of the other threads on here, replacing 

>source(file.path(scriptsDir, "config/flywing_tm_config.R"))

with

>source(file.path(scriptsDir, "config/default_config.R"))

to get the example_data to work.

Doing this with my own set of data results in the following error

>Error in readPNG(ifelse(file.exists(trafoPng), trafoPng, originalPng)) : 
  unable to open /home/rstudio/data/Movie_repository/AmpLifeact/Segmentation/AmpLifeact_050/original.png

**Comment by StephenWallin** [comment]
Ah, I got it. I only have 45 images associated with my movie, so I needed to change 

>render_frame(50) 

to

>render_frame(45)

Awesome, I am glad to be past this road block.

**Comment by etournay** [comment]
Strange, flywing_tm_config.R must work with the demo movie as I compiled the code that automatically generated the Manual. You may have combined the previous path issue or so.
But it cannot work with your own data for which you must use default_config.R

Good that you realized that you only have 45 frames !
Cheers

**Comment by StephenWallin** [comment]
Raphael, 

A few more questions for you regarding the information you provided earlier in this thread regarding use of the geom_point function to plot points rather than displaying polygons. How would I utilize this function in that way? I understand that that the aes(x_pos, y_pos) part of the function allows it to plot the x and y values from whatever table we are working out of. Is there a function in TissueAnalyzer that allows for plotting of centroid points?

Also, is it at all possible to set a limit on values for, as an example, plotting the cell area? Our data sets have some large gaps of membrane staining and the segmentation and subsequent cell overlays display them as very large cells rather than empty space. When they are masked in the movies as well as in the render_frame single slice plots all "normal" sized cells are amongst the smallest values and are therefore displayed as black/very dark blue, with very little ability to differentiate between neighboring cells. If I could set a limit, or determine the axes for the plot, I feel like this should alleviate the problem. 

Thank you once again!
Stephen

**Comment by etournay** [comment]
Hi Stephen,

The answers to all of these questions are in the [manual](https://mpicbg-scicomp.github.io/tissue_miner/user_manual/TM_R-UserManual_v1.0.1.html#cell-area):

1. Use the TM API to get cell area:
`cellArea <- mqf_fg_cell_area(movieDir, rois = c("raw"), cellContour = F)`
It returns a table containing cell_id, area, cell coordinates, but where cell contour points are discarded due to the `cellContour = FALSE` option.
2. The ploting code in section 2.2.2 could be modified as follow:
```
cellArea %>%
  render_frame(1) + 
  geom_point(aes(center_x, center_y, color=area), alpha=0.7) + 
  scale_color_gradientn(name="area (px)",
                       colours=c("black", "blue", "green", "yellow", "red"),
                       limits=c(0,quantile(cellArea$area, probs = 99.9/100)),
                       na.value = "red") +
  ggtitle("Cell area pattern")
```
3. If you want to set area thresholds you have two possibilities. Either you discard all "cells" with a huge area, for example:
`cellArea <- mqf_fg_cell_area(movieDir, rois = c("raw"), cellContour = F) %>% filter(area < 500)`
Or you play with the distribution of cell areas in the ploting code as above in 2. where I remove 0.1% of the area distribution on the right side (upper values):
` limits=c(0,quantile(cellArea$area, probs = 99.9/100))`

I hope this helps. Best wishes

**Comment by StephenWallin** [comment]
Raphael,

Is there a way to utilize tissue miner for single images, rather than movies? We do quite a bit of fixed tissue analysis. If not, is there another piece of software or plugin that you would recommend?

Thank you!
Stephen

**Comment by etournay** [comment]
Hi Stephen,
TissueAnalyzer is excellent for this purpose. TissueMiner only extends it for tracked cell data.
In TissueAnalyzer, you have some ploting functions + ROI management. PLlase, use TissueAnalyzer (Fiji plugin) to work on fixed-tissue/single images.

Best wishes,
R
