### ISSUE TITLE
Example data Downloads

### ISSUE THREAD

**Issue by marcdegennes** [mpicbg-scicomp/tissue_miner#31]
It seems that the downloading of the example data, or of the other provided data, is currently not working properly. 
"curl https://cloud.mpi-cbg.de/index.php/s/SgxxQk5CkIpTLPW/download  | tar -zxvf -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9827    0  9827    0     0  16632      0 --:--:-- --:--:-- --:--:-- 16712
tar: Unrecognized archive format
tar: Error exit delayed from previous errors."

**Comment by etournay** [comment]
Thank you for letting me know. It seems like the server isn't accessible anymore...
@holgerbrandl 
Hi Holger would it be possible to check the status of the link in the following command: `curl https://cloud.mpi-cbg.de/index.php/s/SgxxQk5CkIpTLPW/download | tar -zxvf -`

**Comment by holgerbrandl** [comment]
Hi and sorry for inconvenience marcdegennes.

@etournay you created these shared, see https://github.com/mpicbg-scicomp/tissue_miner/blame/master/README.md#L129

I had only shared https://cloud.mpi-cbg.de/index.php/s/EspCWSQn3k6NKLA/download which is still functional. I guess your login has expired? Do you still have the data so that we could reshare them, or do we need to talk to CBG-CD to recover them?

**Comment by marcdegennes** [comment]
Oh no inconvenience at all we had the example data on another computer.
It was just to inform you.

Best,

Marc

**Comment by etournay** [comment]
Ok, I got it, my MPI account is now disabled. We will fix that internally..

**Comment by etournay** [comment]
Temporarily fixed

**Comment by Ceallaig33** [comment]
Hi @etournay @holgerbrandl 

Looks like maybe these shares with the example datasets have gone stale again. Would it be possible to check?

Thanks for putting together a great software package - we are really looking forward to trying it out!

Cheers,
Mike

**Comment by etournay** [comment]
Strange, I have just tried 

`curl http://bds.mpi-cbg.de/tissue_miner/WT_1.tar.gz | tar -zxvf -`

It works perfectly.

**Comment by holgerbrandl** [comment]
Indeed, I can also not spot any dead resource URLs. I'm also not aware of any changes relating to our filehost `bds.mpi-cbg.de`.

**Comment by etournay** [comment]
I suspect an outdated link in the doc, I will check

**Comment by Ceallaig33** [comment]
@etournay the command you posted now works for me.

The info here: [https://github.com/mpicbg-scicomp/tissue_miner/blob/gh-pages/quickstart_tutorial/other_os/tm_qs_example_data.md#2-download-the-example-data-set-100-mb](url)

probably needs to be updated as you said. This is the error I get: 

```
NIDCDX-01913619:Desktop kellymc$ curl https://cloud.mpi-cbg.de/index.php/s/vC0VqD2Wy4A6uqu/download  | tar -zxvf -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9503  100  9503    0     0   8693      0  0:00:01  0:00:01 --:--:-- 13517
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

thanks
