### ISSUE TITLE
Error 'filter' is longer than time series on cell division analysis

### ISSUE THREAD

**Issue by arumakanorat** [mpicbg-scicomp/tissue_miner#34]
Hello, 
I am working on to use TM for image analyze. I could successfully work through demo dataset with the tutorial. When I started to use own images, the script has skipped cell division analysis with an error about 'filter' is longer than time series. I attached the script including the error region. Cell division video was generated but none of the others, nematic or the graph of cell division rate were not produced. Do you have any suggestions to solve the error? Thanks!

```
Installing package into ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://ftp5.gwdg.de/pub/misc/cran/src/contrib/dtplyr_0.0.2.tar.gz'
Content type 'application/octet-stream' length 12682 bytes (12 KB)
==================================================
downloaded 12 KB

* installing *source* package ‘dtplyr’ ...
** package ‘dtplyr’ successfully unpacked and MD5 sums checked
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (dtplyr)

The downloaded source packages are in
	‘/tmp/RtmpCk4jAO/downloaded_packages’
[1] "using config file /tissue_miner/config/default_config.R"
[1] ""
[1] "Querying the DB..."
Error in stats::filter(x, rep(1/n, n), sides = 2, ...) : 
  'filter' is longer than time series
Calls: mqf_cg_roi_rate_CD ... as.data.frame -> [ -> [.data.table -> ma -> <Anonymous>
Execution halted
```

**Comment by holgerbrandl** [comment]
Are you using a time-series with less than 5 images? We do some smoothing over time for the movies, and at the moment we default to kernel-size of 5 for the smoothing.  See [here](https://github.com/mpicbg-scicomp/tissue_miner/blob/187204ebfe5e81c38feda892379bbd87ab9f9c96/commons/RoiCommons.R#L39)

**Comment by arumakanorat** [comment]
Thanks for replying. I'm using a time-series with 6 images (000, 001,,, 005.tif) as a trial.

**Comment by holgerbrandl** [comment]
Could still be too close for a kernel size of 5 to work. And we also use kernel sizes of 10 in some other parts of TM, which will definitely fail with just 6 timepoints. There is no generic solution I'm afraid.

You could use more images (recommened) or just run those parts of TM that don't smooth over time (which is half of it so it's not recommened). The only actual work-around would be to use a dummy implementation without any smoothing in `smooth_tissue()` in `commons/RoiCommons.R:37`

**Comment by arumakanorat** [comment]
Okay, I will try again with more images! Thanks for your help.

**Comment by etournay** [comment]
Hi, 
thx Holger for replying so quickly. Actually, it depends on the function: if it is `smooth_tissue()`your are right. If it is the basic `ma()` then default options requires 11 frames.
It's on my todo list to automatically adjust the kernel size for the quickstart tuto.

For more advanced user, it is fine as it is since they build their own scripts and therefore control all parameters. 
Cheers,
Rapha
