### ISSUE TITLE
sync docker user UID with actual user UID

### ISSUE THREAD

**Issue by holgerbrandl** [mpicbg-scicomp/tissue_miner#37]
To make sure that directoies mounted into the docker instance can be actually read/write, why don't we follow the scheme suggested on https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
Basically they expose the users's UID in the container and create new user with exactly that ID. Still feels a bit clumsy but it could potentially help to solve the permissions issues here together with @nataliedye

**Comment by etournay** [comment]
Thanks Holger for this solution. I'm currently using a slightly different solution provided by the team of rocker (dockerized RStudio): [https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine](url).
The advantage of this last solution it that it's already working for the RSTUDIO configuration and it's pretty elegant too.
In practice, look at [https://github.com/rocker-org/rocker/tree/master/rstudio/testing](url) to see the implementation. This is how I quickly fixed TM linux permissions for Natalie during my Holiday time ;)
@nataliedye

**Comment by holgerbrandl** [comment]
Thanks for the pointer. Indeed it looks more elegant.
