### ISSUE TITLE
Error rstudio::server::app_armor::enforceRestricted()

### ISSUE THREAD

**Issue by piscitel** [mpicbg-scicomp/tissue_miner#38]
When running the following bits under MacOS 10.13.3 we (me+@holgerbrandl) get the following error:
```bash
docker run -ti  -p 8787:8787 -e USER=rstudio -e PASSWORD=rstudio -v $HOME:/home/rstudio/data etournay/tissue_miner bash
root@3cce66058047:/movies/demo# /usr/lib/rstudio-server/bin/rserver
root@3cce66058047:/movies/demo# rserver[17]: ERROR system error 22 (Invalid argument); OCCURRED AT: rstudio::core::Error rstudio::server::app_armor::enforceRestricted() /home/ubuntu/rstudio/src/cpp/server/ServerAppArmor.cpp:90; LOGGED FROM: int main(int, char* const*) /home/ubuntu/rstudio/src/cpp/server/ServerMain.cpp:506
```
Ideas? workarounds?

**Comment by etournay** [comment]
Yes, it is normal. The R server is not meant to be started this way. It should be started with `/init`.
In addition, it depends on the docker image. If you type in `docker images` in a terminal you'll list all downloaded docker images with the associated tag. Let me know which tag you have.
Best, 
R

**Comment by holgerbrandl** [comment]
Thanks @etournay for coming back to us so quickly.

Indeed running it via kinematic works for me under macos. The docs under `1.3.1 Start and access RStudio within TissueMiner` may want to mention kinematic.

Alternative, could you @piscitel try 
```bash
docker run --name rocker -d -p 8787:8787 -e USER=rstudio -e PASSWORD=rstudio -v $HOME:/home/rstudio/data etournay/tissue_miner
```
as indicated in the manual again on your mac? This works for me as well. Make sure to remove any previous image called `rocker` if present beforehand.
I think it may have worked in the first place already, but `echo "http://$(docker-machine ip default):8787"
` is broken and fails with 
```
Docker machine "default" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
```

Luckily, once it is running (check with `docker ps -a`), you simply access the rstudio webui via `http://localhost:8787`.
