### ISSUE TITLE
original.png images

### ISSUE THREAD

**Issue by veenachatti** [mpicbg-scicomp/tissue_miner#41]
Hi!

I am a predoc in Suzanne's lab, and I have been trying to use TM on my datasets. It worked once! 
However, when I try to get it to work again, it says it needs the original.png file. Which step creates this file? It's missing in the output from TA.
Thanks for answering!

Best,
Veena

**Comment by holgerbrandl** [comment]
Hi Veena, @jandoG will try to schedule a meeting with you to solve this in person, so I'm closing the ticket in here.

**Comment by phbro** [comment]
Hi - I'm trying to run TM on my datasets and am having this same issue. The only difference is that my movie time points are .tif files. Is there a way to solve this?

Thanks!
Beatrice

**Comment by etournay** [comment]
Hi,
original.png files are not generated in TA. They are generated by TissueMiner for display purposes when visualizing data on top of the tissue images. Those files are generated by the first step in the snakemake workflow:
`sm prepare_movie`

[Figure7 Elife TissueMiner](https://doi.org/10.7554/eLife.14334.030)

To force snake make to rerun a step, use the -f option:
`sm -f prepare_movie`
