### ISSUE TITLE
fatal: unable to open /var/run/s6/container_environment/TM_HOME

### ISSUE THREAD

**Issue by Mrc010** [mpicbg-scicomp/tissue_miner#43]
Hi there,

I installed docker and tm on Ubuntu 18.04 w/o problems. Now when I run 
`docker run --rm -ti -u rstudio etournay/tissue_miner`, I get a weird permission error:
`s6-printenv: fatal: unable to open /var/run/s6/container_environment/TM_HOME: Permission denied`. Not clear what's the issue here.

**Comment by Mrc010** [comment]
Now reproduced the same error on Ubuntu 16.04

**Comment by holgerbrandl** [comment]
To start the dockerized rstudio follow section 1.3.1 of the guide https://mpicbg-scicomp.github.io/tissue_miner/user_manual/TM_R-UserManual_v1.0.3.html#how-to-set-up-tissueminer-for-running-api and do
```bash
docker run --name rocker -d -p 8787:8787 -e USER=rstudio -e PASSWORD=rstudio -v $HOME:/home/rstudio/data etournay/tissue_miner
```
instead.

**Comment by etournay** [comment]
Hello @mdkokic !

The dockerized TM tries to start  Rstudio by default, so you must specify an explicit command to overwrite the default and run the automated workflow for example. Or you must start Rstudio with the appropriate command. As @holgerbrandl wrote, if you want to use RStudio, you must type in 
`docker run --name rocker -d -p 8787:8787 -e USER=rstudio -e PASSWORD=rstudio -v $HOME:/home/rstudio/data etournay/tissue_miner`

But if you want do run the automated workflow 
`docker run --rm -ti -v $(dirname $PWD):/movies -w /movies/$(basename $PWD) -u rstudio etournay/tissue_miner sm all`

More info on quickstart tutorials:
[https://github.com/mpicbg-scicomp/tissue_miner/blob/gh-pages/quickstart_tutorial/other_os/tm_qs_example_data.md#first-use-of-tissueminer-with-example-data](https://github.com/mpicbg-scicomp/tissue_miner/blob/gh-pages/quickstart_tutorial/other_os/tm_qs_example_data.md#first-use-of-tissueminer-with-example-data)

There is still one more issue in Linux systems: if you user ID is different from 1000 you may have permission issues when generating the analysis. A work around is to run Linux in a Virtualbox and create an user with the ID 1000 (by default, it is the case). The other advantage of the Virtualbox is that you decide how much resources to allocate (cpu + RAM) to your VM (safer).

R
