### ISSUE TITLE
R tutorial links to example movies are incorrect

### ISSUE THREAD

**Issue by holgerbrandl** [mpicbg-scicomp/tissue_miner#44]
See https://github.com/mpicbg-scicomp/tissue_miner/blob/gh-pages/user_manual/TM_R-UserManual_v1.0.3.Rmd#L1168

Correct links are provided in `README.md`.

To fix it, we need to rerender the tutorial. Do we have any script to do so?

@jandoG @lhersemann

**Comment by etournay** [comment]
Corrected in both Rmd and html file. Thank you for pointing this issue.
Raphael
