### ISSUE TITLE
Question on cell outlines in DB

### ISSUE THREAD

**Issue by YonitMMS** [mpicbg-scicomp/tissue_miner#47]
Hello, we are trying to use TissueMiner to analyze epithelial cell data, but we need to apply a geometrical correction to the segmented cell outlines before calculating area and other geometrical parameters. The DB holds the bonds and vertices for each cell, but does it also hold the full cell outlines somewhere? And if so, could you point us to where?

Thanks very much.
Yonit Maroudas-Sacks
PhD student, Kinneret Keren Lab, Technion

**Comment by etournay** [comment]
Hello Yonit,
Thanks for your message and sorry for my late reply.
Cell outlines are not stored in the DB, but only the vertex coordinates and the connections between them.
To represent cells in TM, we simply draw a straight line between vertices.

Your question is difficult to answer because it depends on how you want to apply the geometrical correction.
If it's an affine transformation, you may apply this transformation on cell vertices. You would only move vertex positions, not the connections. 
Ideally it would be preferable to apply this geometrical correction to the segmentation masks (on the images) and build the database on these corrected data.
I hope this helps !

**Comment by YonitMMS** [comment]
Hi, thanks very much for your response! I ended up just extracting the outlines through matlab, and then applying the geometric correction to the full outline (which is important since the cells in our images are often not very well approximated as simple polygons, so using just the vertices is not sufficient), and after that re-writing the corrected measures for area etc. into the TM databases. 
Best,
Yonit

**Comment by etournay** [comment]
Ok, great, but just to make sure that there is no confusion:
 **the cell parameters (area, elongation nematics, polarity nematics, etc...) that are stored in the DB have been calculated on the full cell outline of the segmentation mask. Therefore, such parameters do not need to be corrected unless the segmentation mask is wrong.** 

For example, in case of a tilted tissue along the z direction, the resulting 2D projection will give rise to geometrical inaccuracies. This can be corrected  by third party programs and must be done before building the DB. TM displays cells as polygons (or dots) to simplify the visualisation and to speed up the display of millions of cells (no need to store all cell outline pixels in the DB). But the display of these contours is NOT used to compute cell parameters. 

FYI, in a next wersion of TM we will store parametrized cell contours to improve the display without losing too much performance in displaying millions of cells: a few parameter (10 to 20) should be enough to recapitulate irregular contours of several hundreds of pixels. 

Best, 
Raphael.

**Comment by YonitMMS** [comment]
Hi Raphael,

Thanks very much. The case for our data is exactly as you suggest; the segmentation masks are 2d projections, whereas the tissue is a curved surface, therefore we separately use the 3d information to apply the geometric correction and calculate the area, perimeter, etc. The visualization as it currently is, using the vertices, is still very useful to us as to get an idea of what is going on, but in our case it will indeed look much better with a fuller representation of the cell contours for the display, since many of the cells are not regular polygons. 

Thanks again for your answers,
Yonit
