### ISSUE TITLE
use simpler sm-dag

### ISSUE THREAD

**Issue by holgerbrandl** [mpicbg-scicomp/tissue_miner#9]
There is a confusing scheme in the snakemake workflow. Indeed we have 3 rules area_movies, db_elongation_movies and state_movies. Area, elongation are state properties as defined in the main text of the manuscript. I think it's clearer to keep seperate rules for area and elongation, as it is :). But I think the state_movies rule should be splited into what it does: grid_movie and cell_density_movie.

You could also merge grid_movie and stripe_movie into a grid_stripe_movies rule. I would do it like that.

**Comment by holgerbrandl** [comment]
### Concerning "state_movies rule should be splited into what it does: grid_movie and cell_density_movie.":
The MakeMovies.R just creates 2 movies anyway do you really want split it into separate tools? Feels a bit overfragmented to me.

### Concerning "merge grid_movie and stripe_movie into a grid_stripe_movies rule."
There is no grid_movie rule. Also keeping movie rendering rules separate gives better cluster usage.

Feel welcome to reassign once we clarified these questions. Since the suggested changes are purely cosmetically we might also want to do these changes later?

**Comment by etournay** [comment]
It's prereferable to split state_movies rule as movies belong to different caterogies (one is state, the other is deformation)
We can just move the grid_movie into the stripe_movies rule that you rename grid_stripe_movies
Thx a lot
